### ISSUE TITLE
Cloud II Wireless

### ISSUE THREAD

**Issue by michalis97500** [franco-giordano/cloud-flight-monitor#4]
Hey, I have a pair of Cloud II Wireless and would love to use this software. Is there a way to figure out what bytes I need to send to my device to get the same reply?

**Comment by franco-giordano** [comment]
Hey, to find mine I simply searched on Github/Google to see if someone else did the same. In your case, I found for example the following repo: https://github.com/Agustin-Jerusalinsky/hyperx-cloud-II-battery/blob/master/battery.py I'm not sure how to get them by reverse-engineering, that's quite difficult AFAIK. Good luck!
